#!/bin/sh

#
# Finds the nearest merge base for a given feature branch.
#

FEATURE_BRANCH=$1

if [ -z "$FEATURE_BRANCH" ]; then
  echo "Usage: git-base-branches FEATURE_BRANCH"
  exit 128
fi

# All refs without the given feature branch 
REFS=$(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v $FEATURE_BRANCH)

MERGE_BASE=$(git merge-base $FEATURE_BRANCH $REFS)
git --no-pager log -1 --decorate $MERGE_BASE
